Raise required KSysGuard version to >=5.20.0
Required since commit 0fcecd6c1e4de21c12dedadbd66f33b35c253ed6.

With 5.19:
src/page/FaceLoader.cpp:55:31: error:
‘class KSysGuard::SensorFaceController’ has no member named ‘setShouldSync’)

Signed-off-by: Andreas Sturmlechner <asturm@gentoo.org>